import type { Track } from "./types";

export const tracks: Track[] = [
  {
    slug: "python-for-ai",
    name: "Python for AI",
    shortName: "Python",
    level: "Beginner",
    tagline: "The language every AI system is written in.",
    description:
      "Start from zero and finish able to load, clean and analyse a real dataset in Python — the foundation every lab in the AI & ML track builds on.",
    status: "active",
    cover: { src: "/images/pair-programming.jpg", alt: "Two developers reading code together on a monitor" },
    modules: [
      {
        slug: "py-foundations",
        title: "Talking to Python",
        summary: "Values, variables, and decisions — the building blocks of every program.",
        labs: ["py-values", "py-decisions"],
        milestone: {
          title: "Your first decision-making program",
          description: "You can store data, compute with it, and write rules that choose between outcomes.",
        },
      },
      {
        slug: "py-collections",
        title: "Working with many values",
        summary: "Lists, loops, text and the everyday toolkit: how code handles a whole dataset, not one number.",
        labs: ["py-lists", "py-loops", "py-strings", "py-toolkit"],
        milestone: {
          title: "Code that scales to any amount of data",
          description: "You can hold a column of data, clean text, and total, filter, count or sort it — with loops or one-line comprehensions.",
        },
      },
      {
        slug: "py-data",
        title: "Organising code and data",
        summary: "Functions, dictionaries, files, errors and JSON — the shape of real data work.",
        labs: ["py-functions", "py-dicts", "py-files", "py-errors", "py-modules"],
        milestone: {
          title: "Real data, from file to answer",
          description: "You can read CSV and JSON, work with records, survive bad data, and package logic into reusable functions.",
        },
      },
      {
        slug: "py-engineering",
        title: "Thinking like a programmer",
        summary: "Classes, debugging and testing — how to read library code and trust your own.",
        labs: ["py-classes", "py-debugging"],
        milestone: {
          title: "Code you can trust",
          description: "You can read and write classes like ML libraries use, find bugs methodically, and prove your code works with tests.",
        },
      },
      {
        slug: "py-capstone",
        title: "Capstone project",
        summary: "Put it all together on a real question with messy data.",
        labs: ["py-project-market"],
        milestone: {
          title: "Python for AI — complete",
          description: "You've taken messy data to a defensible recommendation. You're ready for machine learning.",
        },
      },
      {
        slug: "py-scientific",
        title: "Scientific Python",
        summary: "The libraries data scientists use every day.",
        labs: [],
        planned: [
          { title: "Arrays with NumPy", summary: "Fast maths on whole columns at once." },
          { title: "DataFrames with pandas", summary: "Load, filter and group tables in a few lines." },
          { title: "Plotting your data", summary: "See the pattern before you model it." },
        ],
      },
    ],
    placement: [
      {
        prompt: "What does this print?",
        code: `price = 120\nbags = 3\ntotal = price * bags\nprice = 150\nprint(total)`,
        options: ["360", "450", "150", "Error"],
        answer: 0,
        lab: "py-values",
      },
      {
        prompt: "What does this print?",
        code: `print("12" + "3")`,
        options: ["123", "15", "12 3", "TypeError"],
        answer: 0,
        lab: "py-values",
      },
      {
        prompt: "What does this print?",
        code: `t = 25\nif t > 20:\n    print("warm")\nelif t > 10:\n    print("mild")\nelse:\n    print("cold")`,
        options: ["warm", "warm\nmild", "mild", "cold"],
        answer: 0,
        lab: "py-decisions",
      },
      {
        prompt: "What does this print?",
        code: `data = [4, 8, 15, 16, 23, 42]\nprint(data[-2], data[1:3])`,
        options: ["23 [8, 15]", "16 [4, 8, 15]", "23 [8, 15, 16]", "42 [8, 15]"],
        answer: 0,
        lab: "py-lists",
      },
      {
        prompt: "What does this print?",
        code: `count = 0\nfor x in [3, 12, 7, 20, 1]:\n    if x > 5:\n        count = count + 1\nprint(count)`,
        options: ["3", "2", "5", "39"],
        answer: 0,
        lab: "py-loops",
      },
      {
        prompt: "What does this print?",
        code: `def add(a, b):\n    print(a + b)\n\nresult = add(2, 3)\nprint(result)`,
        options: ["5\nNone", "5\n5", "None", "5"],
        answer: 0,
        lab: "py-functions",
      },
      {
        prompt: "Which line computes the average of a list called `values`?",
        options: ["sum(values) / len(values)", "values.average()", "mean(values)", "len(values) / sum(values)"],
        answer: 0,
        lab: "py-functions",
      },
      {
        prompt: "What does this print?",
        code: `farm = {"crop": "maize", "acres": 2}\nfarm["acres"] += 1\nprint(farm.get("county", "unknown"), farm["acres"])`,
        options: ["unknown 3", "KeyError", "None 3", "unknown 2"],
        answer: 0,
        lab: "py-dicts",
      },
      {
        prompt: "What does this print?",
        code: `counts = {}\nfor c in ["a", "b", "a"]:\n    counts[c] = counts.get(c, 0) + 1\nprint(counts)`,
        options: ["{'a': 2, 'b': 1}", "{'a': 1, 'b': 1}", "{'a': 2}", "KeyError"],
        answer: 0,
        lab: "py-dicts",
      },
      {
        prompt: "What does this print?",
        code: `name = "  Otieno "\nprint(name.strip().upper() + "!")`,
        options: ["OTIENO!", "  OTIENO !", "Otieno!", "otieno!"],
        answer: 0,
        lab: "py-strings",
      },
      {
        prompt: "What does this print?",
        code: `print([n * 10 for n in [1, 5, 2, 8] if n > 2])`,
        options: ["[50, 80]", "[10, 50, 20, 80]", "[5, 8]", "[50, 20, 80]"],
        answer: 0,
        lab: "py-toolkit",
      },
      {
        prompt: "What does this print?",
        code: `try:\n    value = float("n/a")\nexcept ValueError:\n    value = 0.0\nprint(value)`,
        options: ["0.0", "n/a", "ValueError", "None"],
        answer: 0,
        lab: "py-errors",
      },
      {
        prompt: "What does this print?",
        code: `class Model:\n    def fit(self, values):\n        self.mean_ = sum(values) / len(values)\n\nm = Model()\nm.fit([2, 4, 6])\nprint(m.mean_)`,
        options: ["4.0", "12", "[2, 4, 6]", "AttributeError"],
        answer: 0,
        lab: "py-classes",
      },
      {
        prompt: "A row read with `csv.DictReader` is `{\"price\": \"62\"}`. Which expression gives the number 124?",
        options: ['int(row["price"]) * 2', 'row["price"] * 2', 'row["price"] + row["price"]', 'row.price * 2'],
        answer: 0,
        lab: "py-files",
      },
    ],
  },
  {
    slug: "ai-ml",
    name: "AI & Machine Learning",
    shortName: "AI & ML",
    level: "Intermediate",
    tagline: "Train real models on real problems.",
    description:
      "From your first straight-line model to neural networks and image classifiers — every concept built, run, and tested by you.",
    status: "active",
    requires: ["python-for-ai"],
    cover: { src: "/images/maize-field.jpg", alt: "A field of young maize under a blue sky" },
    modules: [
      {
        slug: "ml-foundations",
        title: "How models learn",
        summary: "What training actually is, and how to test a model honestly.",
        labs: ["rainfall-yield"],
        milestone: {
          title: "Your first trained model",
          description: "You can train a model, test it on unseen data, and explain what it learned.",
        },
        planned: [
          { title: "Classify crop health", summary: "Your first classifier: healthy or diseased, from leaf measurements." },
          { title: "When models go wrong", summary: "Overfitting, noisy data, and how to catch both." },
        ],
      },
      {
        slug: "deep-learning",
        title: "Neural networks",
        summary: "From a single line to layers and weights.",
        labs: [],
        planned: [
          { title: "Build a neural network", summary: "Debug a network that isn't learning — on purpose." },
          { title: "Build an image classifier", summary: "Train a model on local images you chose." },
        ],
      },
    ],
  },
  {
    slug: "data-science",
    name: "Data Science",
    shortName: "Data Science",
    level: "Intermediate",
    tagline: "Exploratory analysis, statistics, and storytelling with data.",
    description: "Exploratory analysis, statistics, and storytelling with data.",
    status: "coming-soon",
    requires: ["python-for-ai"],
    modules: [],
  },
  {
    slug: "data-engineering",
    name: "Data Engineering",
    shortName: "Data Eng.",
    level: "Intermediate",
    tagline: "Pipelines, warehouses, and the systems that feed ML models.",
    description: "Pipelines, warehouses, and the systems that feed ML models.",
    status: "coming-soon",
    requires: ["python-for-ai"],
    modules: [],
  },
];
