import type { Track } from "./types";

export const tracks: Track[] = [
  {
    slug: "python-for-ai",
    name: "Python for AI",
    shortName: "Python",
    level: "Beginner",
    tagline: "The language every AI system is written in.",
    description:
      "Start from zero and finish able to load, clean and analyse a real dataset in Python — the foundation every lab in the AI & ML track builds on.",
    status: "active",
    cover: { src: "/images/pair-programming.jpg", alt: "Two developers reading code together on a monitor" },
    modules: [
      {
        slug: "py-foundations",
        title: "Talking to Python",
        summary: "Values, variables, and decisions — the building blocks of every program.",
        labs: ["py-values", "py-decisions"],
        milestone: {
          title: "Your first decision-making program",
          description: "You can store data, compute with it, and write rules that choose between outcomes.",
        },
      },
      {
        slug: "py-collections",
        title: "Working with many values",
        summary: "Lists, loops, text and the everyday toolkit: how code handles a whole dataset, not one number.",
        labs: ["py-lists", "py-loops", "py-strings", "py-toolkit"],
        milestone: {
          title: "Code that scales to any amount of data",
          description: "You can hold a column of data, clean text, and total, filter, count or sort it — with loops or one-line comprehensions.",
        },
      },
      {
        slug: "py-data",
        title: "Organising code and data",
        summary: "Functions, dictionaries, files, errors and JSON — the shape of real data work.",
        labs: ["py-functions", "py-dicts", "py-files", "py-errors", "py-modules"],
        milestone: {
          title: "Real data, from file to answer",
          description: "You can read CSV and JSON, work with records, survive bad data, and package logic into reusable functions.",
        },
      },
      {
        slug: "py-engineering",
        title: "Thinking like a programmer",
        summary: "Classes, debugging and testing — how to read library code and trust your own.",
        labs: ["py-classes", "py-debugging"],
        milestone: {
          title: "Code you can trust",
          description: "You can read and write classes like ML libraries use, find bugs methodically, and prove your code works with tests.",
        },
      },
      {
        slug: "py-capstone",
        title: "Capstone project",
        summary: "Put it all together on a real question with messy data.",
        labs: ["py-project-market"],
        milestone: {
          title: "Python for AI — complete",
          description: "You've taken messy data to a defensible recommendation. You're ready for machine learning.",
        },
      },
      {
        slug: "py-scientific",
        title: "Scientific Python",
        summary: "The libraries data scientists use every day.",
        labs: [],
        planned: [
          { title: "Arrays with NumPy", summary: "Fast maths on whole columns at once." },
          { title: "DataFrames with pandas", summary: "Load, filter and group tables in a few lines." },
          { title: "Plotting your data", summary: "See the pattern before you model it." },
        ],
      },
    ],
    placement: [
      {
        prompt: "What does this print?",
        code: `price = 120\nbags = 3\ntotal = price * bags\nprice = 150\nprint(total)`,
        options: ["360", "450", "150", "Error"],
        answer: 0,
        lab: "py-values",
      },
      {
        prompt: "What does this print?",
        code: `print("12" + "3")`,
        options: ["123", "15", "12 3", "TypeError"],
        answer: 0,
        lab: "py-values",
      },
      {
        prompt: "What does this print?",
        code: `t = 25\nif t > 20:\n    print("warm")\nelif t > 10:\n    print("mild")\nelse:\n    print("cold")`,
        options: ["warm", "warm\nmild", "mild", "cold"],
        answer: 0,
        lab: "py-decisions",
      },
      {
        prompt: "What does this print?",
        code: `data = [4, 8, 15, 16, 23, 42]\nprint(data[-2], data[1:3])`,
        options: ["23 [8, 15]", "16 [4, 8, 15]", "23 [8, 15, 16]", "42 [8, 15]"],
        answer: 0,
        lab: "py-lists",
      },
      {
        prompt: "What does this print?",
        code: `count = 0\nfor x in [3, 12, 7, 20, 1]:\n    if x > 5:\n        count = count + 1\nprint(count)`,
        options: ["3", "2", "5", "39"],
        answer: 0,
        lab: "py-loops",
      },
      {
        prompt: "What does this print?",
        code: `def add(a, b):\n    print(a + b)\n\nresult = add(2, 3)\nprint(result)`,
        options: ["5\nNone", "5\n5", "None", "5"],
        answer: 0,
        lab: "py-functions",
      },
      {
        prompt: "Which line computes the average of a list called `values`?",
        options: ["sum(values) / len(values)", "values.average()", "mean(values)", "len(values) / sum(values)"],
        answer: 0,
        lab: "py-functions",
      },
      {
        prompt: "What does this print?",
        code: `farm = {"crop": "maize", "acres": 2}\nfarm["acres"] += 1\nprint(farm.get("county", "unknown"), farm["acres"])`,
        options: ["unknown 3", "KeyError", "None 3", "unknown 2"],
        answer: 0,
        lab: "py-dicts",
      },
      {
        prompt: "What does this print?",
        code: `counts = {}\nfor c in ["a", "b", "a"]:\n    counts[c] = counts.get(c, 0) + 1\nprint(counts)`,
        options: ["{'a': 2, 'b': 1}", "{'a': 1, 'b': 1}", "{'a': 2}", "KeyError"],
        answer: 0,
        lab: "py-dicts",
      },
      {
        prompt: "What does this print?",
        code: `name = "  Otieno "\nprint(name.strip().upper() + "!")`,
        options: ["OTIENO!", "  OTIENO !", "Otieno!", "otieno!"],
        answer: 0,
        lab: "py-strings",
      },
      {
        prompt: "What does this print?",
        code: `print([n * 10 for n in [1, 5, 2, 8] if n > 2])`,
        options: ["[50, 80]", "[10, 50, 20, 80]", "[5, 8]", "[50, 20, 80]"],
        answer: 0,
        lab: "py-toolkit",
      },
      {
        prompt: "What does this print?",
        code: `try:\n    value = float("n/a")\nexcept ValueError:\n    value = 0.0\nprint(value)`,
        options: ["0.0", "n/a", "ValueError", "None"],
        answer: 0,
        lab: "py-errors",
      },
      {
        prompt: "What does this print?",
        code: `class Model:\n    def fit(self, values):\n        self.mean_ = sum(values) / len(values)\n\nm = Model()\nm.fit([2, 4, 6])\nprint(m.mean_)`,
        options: ["4.0", "12", "[2, 4, 6]", "AttributeError"],
        answer: 0,
        lab: "py-classes",
      },
      {
        prompt: "A row read with `csv.DictReader` is `{\"price\": \"62\"}`. Which expression gives the number 124?",
        options: ['int(row["price"]) * 2', 'row["price"] * 2', 'row["price"] + row["price"]', 'row.price * 2'],
        answer: 0,
        lab: "py-files",
      },
    ],
  },
  {
    slug: "ai-ml",
    name: "AI & Machine Learning",
    shortName: "AI & ML",
    level: "Intermediate",
    tagline: "Train real models on real problems.",
    description:
      "From your first straight-line model to neural networks and image classifiers — every concept built, run, and tested by you.",
    status: "active",
    requires: ["python-for-ai"],
    cover: { src: "/images/maize-field.jpg", alt: "A field of young maize under a blue sky" },
    modules: [
      {
        slug: "ml-scientific",
        title: "Scientific Python",
        summary: "NumPy, pandas and matplotlib — the tools every ML project is built on.",
        labs: ["np-arrays", "pd-dataframes", "viz-basics", "eda"],
        milestone: {
          title: "From raw CSV to real insight",
          description: "You can load, clean, summarise and chart a dataset — and say what it does and doesn't show.",
        },
      },
      {
        slug: "ml-maths",
        title: "Maths for ML, hands-on",
        summary: "The maths models run on — built with code and sliders, not proofs.",
        labs: ["math-vectors", "math-stats", "math-probability", "math-gradients"],
        milestone: {
          title: "The maths behind the magic",
          description: "You can read the maths in an ML explanation and see what it does in code.",
        },
      },
      {
        slug: "ml-foundations",
        title: "How models learn",
        summary: "What training actually is, and how to test a model honestly.",
        labs: ["rainfall-yield", "gd-scratch", "overfitting", "cross-validation"],
        milestone: {
          title: "Models you can trust",
          description: "You can train a model by gradient descent, spot overfitting, and compare models with honest cross-validated scores.",
        },
      },
      {
        slug: "ml-supervised",
        title: "Supervised learning",
        summary: "The workhorse models for predicting categories — and how to measure them honestly.",
        labs: ["logistic", "clf-metrics", "knn", "trees", "boosting", "crop-early-warning"],
        milestone: {
          title: "A classifier you can defend",
          description: "You can build, compare and tune classifiers, choose thresholds from real costs, and ship a capstone early-warning model.",
        },
      },
      {
        slug: "ml-features",
        title: "Features & pipelines",
        summary: "Turning raw columns into inputs a model can learn from — without cheating.",
        labs: ["encoding-scaling", "feature-engineering", "leakage-pipelines"],
        milestone: {
          title: "Production-ready preprocessing",
          description: "You can encode, scale and engineer features, spot leakage, and wrap it all in a pipeline that takes raw data.",
        },
      },
      {
        slug: "ml-unsupervised",
        title: "Unsupervised learning",
        summary: "Finding structure when there are no labels — segments, compressions and anomalies.",
        labs: ["kmeans", "pca", "anomaly", "fraud-watch"],
        milestone: {
          title: "Patterns without answers",
          description: "You can segment, compress and hunt anomalies in unlabelled data — and ship a fraud review queue.",
        },
      },
      {
        slug: "ml-timeseries",
        title: "Time series & forecasting",
        summary: "Predicting what comes next from what came before — honestly.",
        labs: ["ts-patterns", "forecasting", "price-forecast"],
        milestone: {
          title: "Forecasts you can stand behind",
          description: "You can decompose a series, beat seasonal baselines on held-out time, and deliver a forecast with its uncertainty.",
        },
      },
      {
        slug: "deep-learning",
        title: "Neural networks",
        summary: "From a single neuron to image classifiers — built from scratch so nothing is magic.",
        labs: ["perceptron", "backprop", "mlp", "convolutions", "digit-reader"],
        milestone: {
          title: "Neural networks, demystified",
          description: "You've written backpropagation from scratch, trained networks that beat linear models, built a convolution by hand, and shipped a digit reader with a human-review workflow.",
        },
      },
      {
        slug: "ml-nlp",
        title: "Language & LLMs",
        summary: "How machines read — from word counts to transformers and today's large language models.",
        labs: ["text-data", "bag-of-words", "sentiment", "embeddings", "attention", "llms", "feedback-assistant"],
        milestone: {
          title: "You know how machines read",
          description: "From tokens to TF-IDF, sentiment models, embeddings and attention — and you can explain how an LLM generates text, why it hallucinates, and how retrieval grounds it.",
        },
      },
      {
        slug: "ml-responsible",
        title: "Responsible AI & deployment",
        summary: "Building models that are fair, explainable and actually used.",
        labs: [],
        planned: [
          { title: "Bias & fairness", summary: "Who a model fails — with African examples." },
          { title: "Explainability", summary: "Why did the model decide that?" },
          { title: "Privacy & data ethics", summary: "What you may and may not do with people's data." },
          { title: "Deploying a model", summary: "Saving, serving and monitoring a model in the real world." },
        ],
      },
    ],
  },
  {
    slug: "data-science",
    name: "Data Science",
    shortName: "Data Science",
    level: "Intermediate",
    tagline: "Exploratory analysis, statistics, and storytelling with data.",
    description: "Exploratory analysis, statistics, and storytelling with data.",
    status: "coming-soon",
    requires: ["python-for-ai"],
    modules: [],
  },
  {
    slug: "data-engineering",
    name: "Data Engineering",
    shortName: "Data Eng.",
    level: "Intermediate",
    tagline: "Pipelines, warehouses, and the systems that feed ML models.",
    description: "Pipelines, warehouses, and the systems that feed ML models.",
    status: "coming-soon",
    requires: ["python-for-ai"],
    modules: [],
  },
];
